<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="4w_bot">


    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="robot_name" value="4w_bot" />

	<xacro:property name="chassis_mass" value="1"/>
	<xacro:property name="chassis_length" value="0.24765"/>
	<xacro:property name="chassis_width" value="0.2032"/>
	<xacro:property name="chassis_height" value="0.060325"/>

    <xacro:property name="wheel_mass" value="0.1"/>
	<xacro:property name="wheel_radius" value="0.060325"/>
    <xacro:property name="wheel_length" value="0.060325"/>
    <xacro:property name="wheel_chassis_distance" value="0.015875"/>
    <xacro:property name="wheel_x_distance" value="0.0936625"/>
    <xacro:property name="wheel_y_distance" value="${(chassis_width/2)+wheel_chassis_distance+(wheel_length/2)}"/>
    <xacro:property name="wheel_z_distance" value="0.01349375"/>
    <xacro:property name="wheel_joint_type" value="continuous"/>


    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>


    <!-- Base link-->

    <link name="base_link">
    </link>


    <!--Chassis link-->

    <joint name="chassis_joint" type="${wheel_joint_type}">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-chassis_length/2} 0 ${-chassis_height/2}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_width/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass= "${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_width/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Black</material>
    </gazebo>


    <!--Left front wheel link-->

    <joint name="left_front_wheel_joint" type="${wheel_joint_type}">
        <parent link="base_link"/>
        <child link="left_front_wheel"/>
        <origin xyz="${wheel_x_distance} ${wheel_y_distance} -${wheel_z_distance}" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_front_wheel">
        <material>Gazebo/Gray</material>
    </gazebo>


    <!--right front wheel link-->

    <joint name="right_front_wheel_joint" type="${wheel_joint_type}">
        <parent link="base_link"/>
        <child link="right_front_wheel"/>
        <origin xyz="${wheel_x_distance} -${wheel_y_distance} -${wheel_z_distance}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_front_wheel">
        <material>Gazebo/Gray</material>
    </gazebo>


    <!--Left rear wheel link-->

    <joint name="left_rear_wheel_joint" type="${wheel_joint_type}">
        <parent link="base_link"/>
        <child link="left_rear_wheel"/>
        <origin xyz="-${wheel_x_distance} ${wheel_y_distance} -${wheel_z_distance}" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_rear_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_rear_wheel">
        <material>Gazebo/Gray</material>
    </gazebo>


    <!--right rear wheel link-->

    <joint name="right_rear_wheel_joint" type="${wheel_joint_type}">
        <parent link="base_link"/>
        <child link="right_rear_wheel"/>
        <origin xyz="-${wheel_x_distance} -${wheel_y_distance} -${wheel_z_distance}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_rear_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_length}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_rear_wheel">
        <material>Gazebo/Gray</material>
    </gazebo>


</robot>